/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *ajout_liste;
  GtkWidget *ajout_con;
  GtkWidget *vote_liste;
  GtkWidget *id_mdp_vote;
  GtkWidget *liste_cond;
  GtkWidget *tableau_user;
  GtkWidget *Ajout_user;
  GtkWidget *tab_obs;
  GtkWidget *gestion_des_reclamations;
  GtkWidget *ajout_d_une_reclamation;
  GtkWidget *gestion_bureau_de_vote_;
  GtkWidget *ajouter_bureaudevote;
  GtkWidget *modifier_bureau_de_vote_;
  GtkWidget *gestion_election;
  GtkWidget *ajout_election_;
  GtkWidget *authentification_election;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  ajout_liste = create_ajout_liste ();
  gtk_widget_show (ajout_liste);
  ajout_con = create_ajout_con ();
  gtk_widget_show (ajout_con);
  vote_liste = create_vote_liste ();
  gtk_widget_show (vote_liste);
  id_mdp_vote = create_id_mdp_vote ();
  gtk_widget_show (id_mdp_vote);
  liste_cond = create_liste_cond ();
  gtk_widget_show (liste_cond);
  tableau_user = create_tableau_user ();
  gtk_widget_show (tableau_user);
  Ajout_user = create_Ajout_user ();
  gtk_widget_show (Ajout_user);
  tab_obs = create_tab_obs ();
  gtk_widget_show (tab_obs);
  gestion_des_reclamations = create_gestion_des_reclamations ();
  gtk_widget_show (gestion_des_reclamations);
  ajout_d_une_reclamation = create_ajout_d_une_reclamation ();
  gtk_widget_show (ajout_d_une_reclamation);
  gestion_bureau_de_vote_ = create_gestion_bureau_de_vote_ ();
  gtk_widget_show (gestion_bureau_de_vote_);
  ajouter_bureaudevote = create_ajouter_bureaudevote ();
  gtk_widget_show (ajouter_bureaudevote);
  modifier_bureau_de_vote_ = create_modifier_bureau_de_vote_ ();
  gtk_widget_show (modifier_bureau_de_vote_);
  gestion_election = create_gestion_election ();
  gtk_widget_show (gestion_election);
  ajout_election_ = create_ajout_election_ ();
  gtk_widget_show (ajout_election_);
  authentification_election = create_authentification_election ();
  gtk_widget_show (authentification_election);

  gtk_main ();
  return 0;
}

